spring:
  application:
    name: transaction
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      # 如有必要可以配置密码
      # password: yourpassword
      database: 1
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-c0cfcd0b9c5843b8b717d976f273f854
      chat:
        options:
          model: qwen-max-latest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buy?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456

springdoc:
  swagger-ui:
    path: /doc

logging:
  level:
    org.springframework.ai: debug
    com.wu.transaction: debug